branches:
  only:
    - cosm-rb
    - master
    - version_0.3.xx_branch
language: ruby
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - jruby-18mode
 - jruby-19mode
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
